"""Generator for a clean, minimal Flask app.py"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

# We'll write the app.py line by line to a file
# using a heredoc approach in Python

lines = []

def L(s):
    lines.append(s)

L('# -*- coding: utf-8 -*-')
L('"""Mesa 经济沙盘 v3.3 - 纯服务端渲染"""')
L('import io, threading')
L('from flask import Flask, request')
L('from model import EconomyModel')
L('')
L('app = Flask(__name__)')
L('_lock = threading.Lock()')
L('_md = None')
L('_hist = []')
L('_hl = threading.Lock()')
L('_run = False')
L('_stop = threading.Event()')
L('_thr = None')
L('')
L('def init(**kw):')
L('    global _md, _hist, _run, _thr')
L('    d = dict(n_households=20, n_firms=10, n_traders=20,')
L('             tax_rate=0.15, base_interest_rate=0.05, min_wage=7,')
L('             productivity=1.0, subsidy=0.0, gov_purchase=0.0,')
L('             capital_gains_tax=0.10, shock_prob=0.02)')
L('    d.update((k, v) for k, v in kw.items() if v is not None)')
L('    global _run, _thr')
L('    _run = False')
L('    if _thr: _stop.set()')
L('    with _lock: _md = EconomyModel(**d)')
L('    _hist.clear()')
L('    _rec()')
L('')
L('def step():')
L('    global _md')
L('    with _lock:')
L('        if _md: _md.step()')
L('    _rec()')
L('')
L('def _rec():')
L('    global _hist')
L('    with _lock:')
L('        if _md is None: return')
L('        m = _md')
L('        try:')
L('            emp = sum(1 for h in m.households if h.employed)')
L('            nh = len(m.households)')
L('            vol = getattr(m, "stock_volatility", 0.0)')
L('            bdr = getattr(m, "bank_bad_debt_rate", 0.0) * 100')
L('            ent = {')
L('                "cycle": m.cycle,')
L('                "gdp": round(m.gdp),')
L('                "unemp": round(m.unemployment * 100, 1),')
L('                "price": round(getattr(m, "price_index", 100.0), 1),')
L('                "stock": round(m.stock_price, 1),')
L('                "vol": round(vol, 3),')
L('                "bdr": round(bdr, 1),')
L('                "loans": round(m.total_loans_outstanding),')
L('                "rev": round(m.govt_revenue),')
L('                "bankrupt": m.bankrupt_count,')
L('                "gini": round(m.gini, 3),')
L('                "emp": emp, "nh": nh,')
L('                "rate": round(emp / nh * 100 if nh else 0, 1),')
L('            }')
L('        except: ent = {"cycle": getattr(_md, "cycle", 0)}')
L('    with _hl:')
L('        _hist.append(ent)')
L('        if len(_hist) > 500: del _hist[:-500]')
L('')
L('def _svg(vals, color="#3b82f6", w=640, h=180):')
L('    if not vals: vals = [0]')
L('    n = len(vals)')
L('    LP, RP, TP, BP = 48, 8, 8, 28')
L('    W, H = w - LP - RP, h - TP - BP')
L('    mn, mx, rng = min(vals), max(vals), max(mx - mn, 1)')
L('    g = ""')
L('    for i in range(5):')
L('        y = TP + H * i / 4')
L('        v = mx - rng * i / 4')
L('        g += \'<line x1="{x}" y1="{y:.1f}" x2="{x2}" y2="{y:.1f}" stroke="#e2e8f0"/>\' \\
L('            .format(x=LP, x2=LP+W, y=y, y2=y)')
L('        g += \'<text x="{x}" y="{y:.1f}" text-anchor="end" font-size="10" fill="#94a3b8">{v:.0f}</text>\' \\
L('            .format(x=LP-4, y=y+3, v=v)')
L('    pts = " ".join(\'{x:.0f},{y:.0f}\'.format(x=LP+W*i//max(1,n-1), y=TP+H*(1-(v-mn)/rng) \\
L('                  for i, v in enumerate(vals))')
L('    fp = " M {x} {yh} ".format(x=LP, yh=TP+H) + \\
L('        " ".join("L {x:.0f} {y:.0f}".format(x=LP+W*i//max(1,n-1), y=TP+H*(1-(v-mn)/rng) \\
L('                  for i, v in enumerate(vals)) + \\
L('        " L {x2} {yh} Z".format(x2=LP+W, yh=TP+H)')
L('    svg = \'<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="{}" viewBox="0 0 {} {}">\'.format(h, w, h) + g + \\
L('        \'<polyline points="{}" fill="none" stroke="{}" stroke-width="2" stroke-linejoin="round"/>\' \\
L('        .format(pts, color) +')
L('        \'<path d="{}" fill="{}" opacity="0.1"/>\'.format(fp, color) +')
L('        \'<line x1="{}" y1="{}" x2="{}" y2="{}" stroke="#cbd5e1"/><line x1="{}" y1="{}" x2="{}" y2="{}" stroke="#cbd5e1"/>\'.format(LP, TP, LP+W, TP, LP, TP, LP, TP+H) +')
L('        "</svg>"')
L('    return svg')
L('')

L('SCENARIOS = [')
L('    ("ecocrisis", "经济危机(利率15%,税率25%)"),')
L('    ("loose", "宽松政策(利率1%,税率5%)"),')
L('    ("hightax", "高税高补贴(税率40%,工资15)"),')
L('    ("freemarket", "自由市场(利率2%,税率5%)"),')
L('    ("govstim", "政府刺激(购买150)"),')
L('    ("fin_cris", "金融危机(利率20%,税率30%)"),')
L(']')
L('')
L('SCEN_MAP = {')
L('    "ecocrisis": dict(base_interest_rate=0.15, tax_rate=0.25),')
L('    "loose": dict(base_interest_rate=0.01, tax_rate=0.05, subsidy=15.0),')
L('    "hightax": dict(tax_rate=0.40, subsidy=20.0, min_wage=15.0),')
L('    "freemarket": dict(tax_rate=0.05, base_interest_rate=0.02),')
L('    "govstim": dict(gov_purchase=150.0, tax_rate=0.12, subsidy=8.0),')
L('    "fin_cris": dict(base_interest_rate=0.20, tax_rate=0.30, shock_prob=0.15),')
L('}')
L('')
L('SLIDERS = [')
L('    ("n_households", "家庭数量", 5, 80, 5),')
L('    ("n_firms", "企业数量", 3, 40, 1),')
L('    ("tax_rate", "所得税率(%)", 0, 45, 1),')
L('    ("base_interest_rate", "基准利率(%)", 0, 25, 0.5),')
L('    ("min_wage", "最低工资", 0, 20, 0.5),')
L('    ("productivity", "全要素生产率", 0.1, 3, 0.1),')
L('    ("gov_purchase", "政府购买", 0, 200, 5),')
L('    ("shock_prob", "冲击概率(%)", 0, 20, 1),')
L(']')
L('')
L('CHART_KEYS = [("gdp","GDP"),("unemp","失业率(%)"),("gini","基尼系数"),')
L('              ("stock","股价"),("price","物价指数"),("vol","波动率"),')
L('              ("bdr","坏账率(%)"),("loans","信贷总量")]')
L('')
L('CHART_CLR = {')
L('    "gdp":"#16a34a","unemp":"#dc2626","gini":"#9333ea",')
L('    "stock":"#d97706","price":"#64748b","vol":"#f97316",')
L('    "bdr":"#ec4899","loans":"#0891b2"')
L('}')
L('')

L('def _page():')
L('    with _lock:')
L('        if _md is None: cyc, last = 0, {}')
L('        else:')
L('            cyc = _md.cycle')
L('            try:')
L('                emp = sum(1 for h in _md.households if h.employed)')
L('                nh = len(_md.households)')
L('                vol = getattr(_md, "stock_volatility", 0.0)')
L('                bdr = getattr(_md, "bank_bad_debt_rate", 0.0) * 100')
L('                last = {')
L('                    "gdp": round(_md.gdp),')
L('                    "unemp": round(_md.unemployment * 100, 1),')
L('                    "price": round(getattr(_md, "price_index", 100.0), 1),')
L('                    "stock": round(_md.stock_price, 1),')
L('                    "vol": round(vol, 3),')
L('                    "bdr": round(bdr, 1),')
L('                    "loans": round(_md.total_loans_outstanding),')
L('                    "rev": round(_md.govt_revenue),')
L('                    "bankrupt": _md.bankrupt_count,')
L('                    "gini": round(_md.gini, 3),')
L('                    "emp": emp, "nh": nh,')
L('                    "rate": round(emp / nh * 100 if nh else 0, 1),')
L('                }')
L('            except: last = {}')
L('    with _hl: hist = list(_hist)')
L('')
L('    ck = request.args.get("chart", "gdp")')
L('    cv = [h.get(ck, 0) for h in hist]')
L('    svg_html = _svg(cv, color=CHART_CLR.get(ck, "#3b82f6"))')
L('')
L('    st = [')
L('        ("gdp","GDP","int",False),')
L('        ("unemp","失业率","pct",last.get("unemp",0)>15),')
L('        ("price","物价","dec1",False),')
L('        ("stock","股价","dec1",False),')
L('        ("gini","基尼","dec3",last.get("gini",0)>0.4),')
L('        ("rate","就业率","pct",False),')
L('        ("vol","波动率","dec3",last.get("vol",0)>0.3),')
L('        ("bdr","坏账率","pct",last.get("bdr",0)>10),')
L('        ("bankrupt","破产","int",last.get("bankrupt",0)>0),')
L('        ("loans","贷款","int",False),')
L('        ("rev","政府收入","int",False),')
L('    ]')
L('')
L('    atype = request.args.get("atype", "household")')
L('    agents = ""')
L('    with _lock:')
L('        if _md:')
L('            if atype == "household":')
L('                tm = {"low":"低收入","middle":"中收入","high":"高收入"}')
L('                for h in _md.households:')
L('                    tier = tm.get(str(getattr(h,"income_tier","")),"?")')
L('                    st2 = "就业" if h.employed else "失业"')
L('                    agents += "<div style=\'font-family:monospace;font-size:11px;background:#f8fafc;padding:2px 8px;margin-bottom:2px;border-radius:4px\'>H")
L('                    agents += str(h.unique_id) + " 现:" + str(int(h.cash)) + " 富:" + str(int(h.wealth))')
L('                    agents += " " + st2 + "/" + str(int(h.salary)) + " 股:" + str(getattr(h,"shares_owned",0)) + " [" + tier + "]</div>"')
L('            elif atype == "firm":')
L('                for f in _md.firms:')
L('                    agents += "<div style=\'font-family:monospace;font-size:11px;background:#f8fafc;padding:2px 8px;margin-bottom:2px;border-radius:4px\'>F")
L('                    agents += str(f.unique_id) + " 现:" + str(int(f.cash)) + " 富:" + str(int(f.wealth))')
L('                    agents += " 产:" + str(round(f.production,1)) + " 库:" + str(round(f.inventory,1)) + " 员:" + str(f.employees) + "</div>"')
L('            elif atype == "trader":')
L('                for t in _md.traders:')
L('                    agents += "<div style=\'font-family:monospace;font-size:11px;background:#f8fafc;padding:2px 8px;margin-bottom:2px;border-radius:4px\'>T")
L('                    agents += str(t.unique_id) + " 现:" + str(int(t.cash)) + " 富:" + str(int(t.wealth)) + " 股:" + str(getattr(t,"shares",0)) + "</div>"')
L('            elif atype == "bank":')
L('                for b in _md.banks:')
L('                    agents += "<div style=\'font-family:monospace;font-size:11px;background:#f8fafc;padding:2px 8px;margin-bottom:2px;border-radius:4px\'>B")
L('                    agents += str(b.unique_id) + " 准:" + str(int(getattr(b,"reserves",0))) + " 富:" + str(int(b.wealth)) + "</div>"')
L('')
L('    # Build HTML as list of strings')
L('    h = []')
L('    h.append("<!DOCTYPE html><html lang=zh><head><meta charset=utf-8><meta name=viewport content=width=device-width,initial-scale=1>")
L('    h.append("<title>经济沙盘 v3.3</title>")
L('    h.append("<style>")
L('    h.append("* { box-sizing: border-box; margin: 0; padding: 0; }")
L('    h.append("body { font-family: system-ui, sans-serif; background: #f8fafc; color: #1e293b; padding: 16px; font-size: 14px; max-width: 960px; margin: 0 auto; }")
L('    h.append("h1 { font-size: 20px; margin-bottom: 12px; }")
L('    h.append("h2 { font-size: 11px; color: #64748b; margin-bottom: 8px; text-transform: uppercase; letter-spacing: .05em; }")
L('    h.append(".card { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; margin-bottom: 10px; }")
L('    h.append(".ctrl { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; margin-bottom: 10px; }")
L('    h.append(".btn { border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-size: 13px; font-family: inherit; }")
L('    h.append(".bg { background: #16a34a; color: #fff } .bg:hover { background: #15803d }")
L('    h.append(".bb { background: #3b82f6; color: #fff } .bb:hover { background: #2563eb }")
L('    h.append(".bo { background: #d97706; color: #fff } .bo:hover { background: #b45309 }")
L('    h.append(".br { background: #dc2626; color: #fff } .br:hover { background: #b91c1c }")
L('    h.append(".c2 { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }")
L('    h.append("@media(max-width: 600px) { .c2 { grid-template-columns: 1fr; } }")
L('    h.append(".sc { display: grid; grid-template-columns: repeat(auto-fill, minmax(115px, 1fr)); gap: 8px; }")
L('    h.append(".sc > div { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 10px; }")
L('    h.append(".sl { font-size: 10px; color: #94a3b8; text-transform: uppercase; }")
L('    h.append(".sv { font-size: 18px; font-weight: 700; color: #0f172a; margin-top: 2px; }")
L('    h.append(".dw { color: #d97706; } .dr { color: #dc2626; } .dg { color: #16a34a; }")
L('    h.append(".tabs { display: flex; gap: 4px; flex-wrap: wrap; margin-bottom: 8px; }")
L('    h.append(".tb { background: #e2e8f0; color: #475569; border: none; padding: 5px 10px; border-radius: 5px; cursor: pointer; font-size: 12px; font-family: inherit; margin: 2px; }")
L('    h.append(".ta { background: #3b82f6; color: #fff; border: none; padding: 5px 10px; border-radius: 5px; cursor: pointer; font-size: 12px; font-family: inherit; margin: 2px; }")
L('    h.append("select { width: 100%; padding: 6px; border-radius: 6px; border: 1px solid #cbd5e1; background: #fff; font-size: 13px; font-family: inherit; margin-bottom: 8px; }")
L('    h.append(".srow { margin-bottom: 6px; }")
L('    h.append(".slbl { display: flex; justify-content: space-between; margin-bottom: 2px; font-size: 13px; color: #475569; }")
L('    h.append("input[type=range] { width: 100%; accent-color: #3b82f6; height: 4px; }")
L('    h.append(".alist { max-height: 170px; overflow-y: auto; font-size: 12px; line-height: 1.7; }")
L('    h.append(".cyc { color: #94a3b8; margin-left: auto; }")
L('    h.append("</style></head><body>")
L('    h.append("<h1>经济沙盘 <span style=\'color:#3b82f6\'>v3.3</span> <span class=cyc>第 " + str(cyc) + " 轮</span></h1>")
L('    h.append("<div class=card ctrl>")
L('    h.append("<form method=get style=display:inline><button type=submit name=action value=play class=\"btn bg\">播放</button></form>")
L('    h.append("<form method=get style=display:inline><button type=submit name=action value=pause class=\"btn bo\">暂停</button></form>")
L('    h.append("<form method=get style=display:inline><button type=submit name=action value=step class=\"btn bb\">单步</button></form>")
L('    h.append("<form method=get style=display:inline><button type=submit name=action value=reset class=\"btn br\">重置</button></form>")
L('    h.append("<span class=cyc style=\'margin-left:12px\'>第 " + str(cyc) + " 轮</span>")
L('    h.append("</div>")
L('    h.append("<div class=card><h2>宏观指标</h2><div class=sc>")
L('    for k, lbl, typ, warn in st:')
L('        v = last.get(k, 0)')
L('        cls = "dw" if warn else ""')
L('        if typ == "int": fv = "{:,}".format(int(v))')
L('        elif typ == "pct": fv = "{:.1f}%".format(v)')
L('        elif typ == "dec1": fv = "{:.1f}".format(v)')
L('        else: fv = "{:.3f}".format(v)')
L('        h.append("<div><div class=sl>" + lbl + "</div><div class=\"sv " + cls + "\">" + fv + "</div></div>")')
L('    h.append("</div></div>")
L('    h.append("<div class=card><h2>图表</h2><div class=tabs>")
L('    for fk, fl in CHART_KEYS:')
L('        cls = "ta" if fk == ck else "tb"')
L('        h.append("<form method=get style=display:inline><button type=submit name=chart value=\\"" + fk + "\\" class=\\"" + cls + "\\">" + fl + "</button></form>")')
L('    h.append("</div>" + svg_html + "</div>")
L('    h.append("<div class=c2>")
L('    h.append("<div class=card><h2>经济参数</h2><form method=get>")
L('    for k, lbl, mn, mx, st_v in SLIDERS:')
L('        v = getattr(_md, k, None) if _md else None')
L('        if k in ("tax_rate", "base_interest_rate", "shock_prob"):')
L('            dv = round((v or 0) * 100, 1)')
L('            unit = "%"')
L('        else:')
L('            dv = v if v is not None else (20 if k == "n_households" else 10 if k == "n_firms" else 0)')
L('            unit = ""')
L('        h.append("<div class=srow><div class=slbl><span>" + lbl + "</span><b>" + str(dv) + unit + "</b></div>")
L('        h.append("<input type=range name=\\"" + k + "\\" min=\\"" + str(mn) + "\\" max=\\"" + str(mx) + "\\" step=\\"" + str(st_v) + "\\" value=\\"" + str(dv) + "\\"></div>")')
L('    h.append("<button type=submit name=action value=apply_param class=\"btn bb\" style=\'margin-top:8px;width:100%\'>应用参数</button>")
L('    h.append("</form></div>")
L('    h.append("<div class=card><h2>预设场景</h2><form method=get>")
L('    h.append("<select name=scen><option value=\\'\\'>-- 选择场景 --</option>")
L('    for sv, sl in SCENARIOS:')
L('        h.append("<option value=\\"" + sv + "\\">" + sl + "</option>")')
L('    h.append("</select>")
L('    h.append("<button type=submit name=action value=apply_scen class=\"btn bb\" style=\'width:100%;margin-bottom:12px\'>应用场景</button>")
L('    h.append("</form>")
L('    h.append("<h2>Agent 详情</h2><div class=tabs>")
L('    for av, al in [("household","家庭"),("firm","企业"),("trader","交易者"),("bank","银行")]:')
L('        cls = "ta" if av == atype else "tb"')
L('        h.append("<form method=get style=display:inline><button type=submit name=atype value=\\"" + av + "\\" class=\\"" + cls + "\\">" + al + "</button></form>")')
L('    h.append("</div><div class=alist>" + (agents or "<div style=\'color:#94a3b8\'>无</div>") + "</div>")
L('    h.append("</div></div>")
L('    h.append("<div class=card><form method=get><button type=submit name=action value=export_csv class=\"btn bb\">下载 CSV</button></form></div>")
L('    h.append("</body></html>")')
L('    return "\\n".join(h)')
L('')
L('@app.route("/")')
L('def index():')
L('    global _run, _thr')
L('    act = request.args.get("action", "")')
L('    if act == "step": step()')
L('    elif act == "play":')
L('        _run = True')
L('        if not (_thr and _thr.is_alive()):')
L('            _stop.clear()')
L('            _thr = threading.Thread(target=_play_loop, daemon=True)')
L('            _thr.start()')
L('    elif act == "pause": _run = False')
L('    elif act == "reset": init()')
L('    elif act == "apply_param":')
L('        p = {}')
L('        for k in ("n_households","n_firms","min_wage","productivity","gov_purchase"):')
L('            v = request.args.get(k)')
L('            if v:')
L('                try: p[k] = float(v)')
L('                except: pass')
L('        for k in ("tax_rate","base_interest_rate","shock_prob"):')
L('            v = request.args.get(k)')
L('            if v:')
L('                try: p[k] = float(v) / 100')
L('                except: pass')
L('        if p: init(**p)')
L('    elif act == "apply_scen":')
L('        sc = request.args.get("scen", "")')
L('        if sc in SCEN_MAP: init(**SCEN_MAP[sc])')
L('    elif act == "export_csv":')
L('        buf = io.StringIO()')
L('        with _hl: h = list(_hist)')
L('        if h:')
L('            keys = list(h[0].keys())')
L('            buf.write(",".join(keys) + "\\n")')
L('            for r in h:')
L('                buf.write(",".join(str(r.get(k, "")) for k in keys) + "\\n")')
L('        from flask import Response')
L('        return Response(buf.getvalue().encode("utf-8"), mimetype="text/csv", headers={"Content-Disposition": "attachment; filename=economy.csv"})')
L('    return _page()')
L('')
L('def _play_loop():')
L('    global _run')
L('    while not _stop.wait(0.5):')
L('        if _run: step()')
L('')
L('if __name__ == "__main__":')
L('    init()')
L('    print("经济沙盘 v3.3: http://127.0.0.1:8523")')
L('    app.run(host="0.0.0.0", port=8523, debug=False, threaded=True)')

code = '\n'.join(lines)
with open('C:/Users/Kanyun/.qclaw/workspace/mesa-econ/app.py', 'w', encoding='utf-8') as f:
    f.write(code)

print('Written:', len(code), 'chars,', len(lines), 'lines')

import py_compile
try:
    py_compile.compile('C:/Users/Kanyun/.qclaw/workspace/mesa-econ/app.py', doraise=True)
    print('SYNTAX OK')
except py_compile.PyCompileError as e:
    print('SYNTAX ERROR:', e)
